### PR TITLE
Add flag for enum parameters

### PR DESCRIPTION
**Pull request by messmerd**
See the proposal here: https://github.com/free-audio/clap/discussions/357

This PR adds a `CLAP_PARAM_IS_ENUM` flag to `clap_param_info_flags` to denote an enum parameter.

This flag tells the host when a parameter represents a set of named options mapped to integers, which can help the host decide how to present the parameter to users in its UI.

### CODE REVIEW

**Comment by defiantnerd** [comment]
I think this is really useful PR.

**Comment by abique** [comment]
Maybe it needs a comment to say that the enum isn't allowed to have "holes" between min and max?

**Comment by defiantnerd** [comment]
> Maybe it needs a comment to say that the enum isn't allowed to have "holes" between min and max?

Maybe, although it should be totally clear. You can't have holes in a normal parameter, too.

**Comment by messmerd** [comment]
Maybe I could add this wording?
> _These named options should be available via value_to_text() for each integer value within its [min, max] range._

**Review by abique — CHANGES_REQUESTED** [review]
If the param have `IS_ENUM` then it must have `IS_STEPPED`.

I prefer to say it that way rather than implies.

**Comment by abique** [comment]
Maybe I'd put the comment like this.

```C
// Indicates that this parameter represents an enumerated value.
// If you set this flag, then you must set CLAP_PARAM_IS_STEPPED too.
// All values from min to max must have a non blank value_to_text().
```

**Comment by abique** [comment]
Thank you :+1:

**Comment by baconpaul** [comment]
Oh this is great and I'll use it all the time!

**Pull request merged**
