### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by unfa**
Fixed a minor linguistic error

### CODE REVIEW

**Comment by unfa** [comment]
I wanted to check out the CLA, but the page seems to be broken:
image

**Comment by robbert-vdh** [comment]
Did you try reloading the page? For me it takes about a second after the initial page load for the form to show up (it's lazy loaded using AJAX, also wow I haven't heard anyone use that term by name in a long time).

**Comment by abique** [comment]
LGTM, just need the CLA now.

**Comment by abique** [comment]
Maybe it is because of brave? It prevents loading some resources?

**Comment by baconpaul** [comment]
I also dont' see it in safari / mac this morning

**Comment by abique** [comment]
I can see that: 
image

**Comment by abique** [comment]
Maybe try to clear your cache?

**Comment by abique** [comment]
I've applied manually this change to the next branch.
Thanks!

**Comment by unfa** [comment]
The CLA site worked for me today. Yay!

**Comment by abique** [comment]
Ah Nice :-)

**Pull request closed without merging**
