### PR TITLE
Fix typos in various files

### PR DESCRIPTION
**Pull request by joshnatis**
Does what it says on the tin :). Thanks for your great work!! Very exciting

I structured the fixes as separate commits so that it would be easier to revert any changes you don't like. I'll squash them all before merging.

I tried to not be too overbearing with the corrections, apologies if some of them seem pedantic.

--
Food for thought, https://drewdevault.com/2018/10/05/Dont-sign-a-CLA.html

### CODE REVIEW

**Comment by joshnatis** [comment]
Another thing to keep in mind for consistency is the capitalization of 'GUI' (or lack thereof). Sometimes you have it uppercased sometimes you don't, probably best to stick with one.

**Comment by abique** [comment]
Hi,
Thank you very much for that pull request!
Please could you make it for the branch next instead?
Thank you again :+1:

**Comment by joshnatis** [comment]
Oops lol, sorry about that. Looks like I have some changes to make : ), one second

**Review by abique — APPROVED** [review]

**Comment by abique** [comment]
I'm very happy with your PR, thank you so much :+1:

**Pull request merged**
