### PR TITLE
Corrected reference to clap_plugin_audio_ports members.

### PR DESCRIPTION
**Pull request by spongeboburu**
The correct names are now referenced in the documentation.

### CODE REVIEW

**Comment by abique** [comment]
Hi,
I've made your change target the next branch instead.
Please can you adjust the diff?
Cheers,

**Comment by spongeboburu** [comment]
Ah, sorry, I didn't realize the workflow. Of course!

**Comment by spongeboburu** [comment]
Sorry for the confusion, while I did use github for many years in my work we use gitlab so I haven't been on github for a few years. I think I have checked all the boxes now, thanks for being patient!

**Comment by abique** [comment]
@spongeboburu you have dropped one line that you shouldn't.

**Comment by abique** [comment]
Hello,

Thank you for the PR, I've merged it and then restored the lost line. :-)

**Pull request merged**
